In [1]:
# implementing a simple AND gate using perceptron
import numpy as np
# input features
input = np.array([[0,0],[0,1],[1,0],[1,1]])
input.shape

(4, 2)

In [2]:
print(input)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]


In [3]:
# output
target = np.array([[0],[0],[0],[1]])
print(target)

[[0]
 [0]
 [0]
 [1]]


In [4]:
#output
weights = np.array([[0.1],[0.2]])
print(weights)

[[0.1]
 [0.2]]


In [5]:
# bias and learning rate
bias = 1
lr = 0.05

In [6]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_der(x):
    return sigmoid(x)*(1-sigmoid(x))

In [7]:
# define the main logic in each iteration and in total there are 10000 iteration
for epoch in range(10000):
    inp_o = np.dot(input, weights) + bias
    out_o = sigmoid(inp_o)
    error = out_o - target
    derr_out = error
    derr_o_i = sigmoid_der(out_o)
    mul_der = derr_out * derr_o_i
    input_t = input.T
    final_der = np.dot(input_t, mul_der)
    weights-=lr*final_der
    for i in mul_der:
        bias-=lr*i
    print(weights)
    print(bias)

[[0.09412973]
 [0.193986  ]]
[0.97779454]
[[0.08836919]
 [0.18807885]]
[0.95577419]
[[0.08271954]
 [0.18227974]]
[0.93394079]
[[0.07718185]
 [0.17658975]]
[0.91229608]
[[0.07175712]
 [0.17100991]]
[0.89084166]
[[0.06644623]
 [0.16554113]]
[0.86957902]
[[0.06125002]
 [0.16018428]]
[0.84850951]
[[0.0561692 ]
 [0.15494011]]
[0.82763436]
[[0.05120442]
 [0.1498093 ]]
[0.80695466]
[[0.04635622]
 [0.14479243]]
[0.78647138]
[[0.04162506]
 [0.13989002]]
[0.76618533]
[[0.03701131]
 [0.13510247]]
[0.74609722]
[[0.03251524]
 [0.1304301 ]]
[0.72620759]
[[0.02813703]
 [0.12587314]]
[0.70651688]
[[0.02387678]
 [0.12143176]]
[0.68702537]
[[0.0197345]
 [0.117106 ]]
[0.66773322]
[[0.01571009]
 [0.11289584]]
[0.64864046]
[[0.0118034 ]
 [0.10880117]]
[0.629747]
[[0.00801418]
 [0.10482181]]
[0.61105261]
[[0.00434208]
 [0.10095748]]
[0.59255695]
[[0.0007867 ]
 [0.09720783]]
[0.57425956]
[[-0.00265244]
 [ 0.09357244]]
[0.55615985]
[[-0.00597592]
 [ 0.09005081]]
[0.53825714]
[[-0.00918437]
 [ 0.08664237]]
[0.

In [8]:
print(weights)

[[5.81317925]
 [5.81318153]]


In [9]:
print(bias)

[-9.0082875]


In [10]:
# predicting output for 1,0

input = np.array([1,0])
result1 = np.dot(input, weights) + bias
result2 = sigmoid(result1)


In [11]:
print(result2)

[0.03935022]
